Added advanced features like condition parsing for aws iac template
prancer-io/cloud-validation-framework pull request #316
Opened 2021-08-03 11:56 UTC by harshilswan

2021-08-03 14:49 UTC, farchide requested changes
@harshilswan make sure to link PR to an existing issue

2021-08-05 07:09 UTC, vatsalgit5118 approved these changes

2021-08-05 07:16 UTC, harshilswan commented
> @harshilswan make sure to link PR to an existing issue

I have linked the issue #304

2021-08-05 15:20 UTC, farchide approved these changes

2021-08-05 15:51 UTC, merged