File system connector
prancer-io/cloud-validation-framework pull request #38
Opened 2019-10-18 18:58 UTC by patidarpraveen244

Allowing to read json from file system.

2019-10-22 03:21 UTC, ajeybk approved these changes

2019-10-22 03:23 UTC, ajeybk commented
Fix the tests that are failing, then we should be able to merge.

2019-10-22 05:18 UTC, farchide requested changes

2019-10-22 05:18 UTC, farchide commented on docs/docs/snapshots/json.md
>                  "source": "gitConnector",
type should be `filesystem`

2019-10-22 05:18 UTC, farchide commented on realm/fileSystemConnector.json
> +  "companyName": "prancer-test",
we should have "type":"filesystem" here

2019-10-23 07:36 UTC, patidarpraveen244 commented on docs/docs/snapshots/json.md
>                  "source": "gitConnector",
Done.

2019-10-23 07:36 UTC, patidarpraveen244 commented on realm/fileSystemConnector.json
> +  "companyName": "prancer-test",
Done.

2019-10-24 09:37 UTC, patidarpraveen244 commented
@farchide please take a look at the changes. Also I have created another pull request for the docs.

2019-10-25 06:26 UTC, ajeybk approved these changes

2019-10-25 06:36 UTC, farchide approved these changes

2019-10-25 06:36 UTC, merged